Repository magento/glossary, pull requests merged in 2019-06, with the labels that each got.

#20 Add favicon to Layout
  src/components/Layout/favicon.js
  src/components/Layout/layout.js
Labels: Technical

#22 [BugFix] Upper case bug
  src/components/Layout/layout.js
Labels: bug

#25 Add logic for creating JSON files
  gatsby-node.js
Labels: Site improvement, enhancement

#26 Fix typo
  src/terms/adobe.md
Labels: Editorial
